"""Built-in deterministic domain profiles for verified memory."""

COMMON_SOURCE_PRIORITY = [
    "official_vendor",
    "official_release_notes",
    "official_github",
    "government_or_institution",
    "trusted_technical_blog",
    "wikipedia_background",
    "forum_or_reddit",
    "unknown",
]

GENERAL_STALENESS = {
    "software_behavior": 60,
    "microsoft_365": 30,
    "pricing": 3,
    "news": 1,
    "game_patch": 7,
    "law_or_regulation": 30,
    "internal_sop": 180,
    "personal_preference": None,
    "historical_fact": None,
}

DEFAULT_DOMAIN_PROFILES = {
    "general": {
        "name": "general",
        "description": "General verified-memory policy for mixed knowledge.",
        "default_stale_after_days_by_claim_type": GENERAL_STALENESS,
        "source_priority": COMMON_SOURCE_PRIORITY,
        "web_search_allowed": True,
        "manual_approval_required": False,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": False,
    },
    "it_software": {
        "name": "it_software",
        "description": "Software, IT operations, devices, SaaS, and troubleshooting.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "driver_or_firmware": 30,
            "internal_sop": 180,
        },
        "source_priority": COMMON_SOURCE_PRIORITY,
        "web_search_allowed": True,
        "manual_approval_required": False,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": False,
    },
    "microsoft_365": {
        "name": "microsoft_365",
        "description": "Microsoft 365, Teams, SharePoint, Entra, and Intune behavior.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "software_behavior": 30,
            "microsoft_365": 30,
            "pricing": 3,
        },
        "source_priority": COMMON_SOURCE_PRIORITY,
        "web_search_allowed": True,
        "manual_approval_required": False,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": False,
    },
    "medical": {
        "name": "medical",
        "description": "Medical and health information with conservative approval requirements.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "medication_guidance": 30,
            "general_health_info": 90,
            "personal_doctor_instruction": None,
        },
        "source_priority": [
            "government_or_institution",
            "official_vendor",
            "trusted_technical_blog",
            "wikipedia_background",
            "forum_or_reddit",
            "unknown",
        ],
        "web_search_allowed": True,
        "manual_approval_required": True,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": True,
    },
    "legal": {
        "name": "legal",
        "description": "Legal, compliance, policy, and contract-related information.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "law_or_regulation": 30,
            "contract_clause": None,
            "legal_news": 7,
        },
        "source_priority": [
            "government_or_institution",
            "official_vendor",
            "trusted_technical_blog",
            "wikipedia_background",
            "forum_or_reddit",
            "unknown",
        ],
        "web_search_allowed": True,
        "manual_approval_required": True,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": True,
    },
    "finance": {
        "name": "finance",
        "description": "Finance, market, tax, pricing, and banking information.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "stock_price": 1,
            "exchange_rate": 1,
            "pricing": 3,
            "tax_rule": 30,
        },
        "source_priority": COMMON_SOURCE_PRIORITY,
        "web_search_allowed": True,
        "manual_approval_required": True,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": True,
    },
    "gaming": {
        "name": "gaming",
        "description": "Games, patch notes, server status, and gaming hardware/software behavior.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "patch_status": 7,
            "server_status": 1,
            "game_patch": 7,
        },
        "source_priority": COMMON_SOURCE_PRIORITY,
        "web_search_allowed": True,
        "manual_approval_required": False,
        "never_final_sources": ["unknown", "blocked_low_quality"],
        "requires_disclaimer": False,
    },
    "academic": {
        "name": "academic",
        "description": "Academic research, papers, datasets, and literature review notes.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "active_research_area": 90,
            "historical_paper": None,
        },
        "source_priority": [
            "government_or_institution",
            "official_github",
            "trusted_technical_blog",
            "wikipedia_background",
            "forum_or_reddit",
            "unknown",
        ],
        "web_search_allowed": True,
        "manual_approval_required": False,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": False,
    },
    "personal_knowledge": {
        "name": "personal_knowledge",
        "description": "Personal preferences and private user knowledge.",
        "default_stale_after_days_by_claim_type": {
            **GENERAL_STALENESS,
            "personal_preference": None,
            "personal_fact": None,
        },
        "source_priority": ["user_provided", "local_document", *COMMON_SOURCE_PRIORITY],
        "web_search_allowed": False,
        "manual_approval_required": True,
        "never_final_sources": ["forum_or_reddit", "unknown", "blocked_low_quality"],
        "requires_disclaimer": False,
    },
}
